/* soapClient.c
   Generated by gSOAP 2.8.71 for auth.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.71 2020-11-26 16:44:53 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__Random(struct soap *soap, const char *soap_endpoint, const char *soap_action, char **RandomReturn)
{	struct ns1__Random soap_tmp_ns1__Random;
	struct ns1__RandomResponse *soap_tmp_ns1__RandomResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.30.202.27:8086/app/services/AuthService";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__Random(soap, &soap_tmp_ns1__Random);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__Random(soap, &soap_tmp_ns1__Random, "ns1:Random", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__Random(soap, &soap_tmp_ns1__Random, "ns1:Random", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!RandomReturn)
		return soap_closesock(soap);
	*RandomReturn = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__RandomResponse = soap_get_ns1__RandomResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__RandomResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (RandomReturn && soap_tmp_ns1__RandomResponse->RandomReturn)
		*RandomReturn = *soap_tmp_ns1__RandomResponse->RandomReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__AuthSecAssert(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_inStr, char **_AuthSecAssertReturn)
{	struct ns1__AuthSecAssert soap_tmp_ns1__AuthSecAssert;
	struct ns1__AuthSecAssertResponse *soap_tmp_ns1__AuthSecAssertResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.30.202.27:8086/app/services/AuthService";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp_ns1__AuthSecAssert._inStr = _inStr;
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__AuthSecAssert(soap, &soap_tmp_ns1__AuthSecAssert);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__AuthSecAssert(soap, &soap_tmp_ns1__AuthSecAssert, "ns1:AuthSecAssert", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__AuthSecAssert(soap, &soap_tmp_ns1__AuthSecAssert, "ns1:AuthSecAssert", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_AuthSecAssertReturn)
		return soap_closesock(soap);
	*_AuthSecAssertReturn = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__AuthSecAssertResponse = soap_get_ns1__AuthSecAssertResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__AuthSecAssertResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (_AuthSecAssertReturn && soap_tmp_ns1__AuthSecAssertResponse->_AuthSecAssertReturn)
		*_AuthSecAssertReturn = *soap_tmp_ns1__AuthSecAssertResponse->_AuthSecAssertReturn;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
