/* soapClient.c
   Generated by gSOAP 2.8.71 for user.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.71 2020-11-26 16:30:31 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__Challenge(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_challenge, char **_ChallengeReturn)
{	struct ns1__Challenge soap_tmp_ns1__Challenge;
	struct ns1__ChallengeResponse *soap_tmp_ns1__ChallengeResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.30.202.81:8086/app/services/RNService";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp_ns1__Challenge._challenge = _challenge;
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__Challenge(soap, &soap_tmp_ns1__Challenge);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__Challenge(soap, &soap_tmp_ns1__Challenge, "ns1:Challenge", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__Challenge(soap, &soap_tmp_ns1__Challenge, "ns1:Challenge", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_ChallengeReturn)
		return soap_closesock(soap);
	*_ChallengeReturn = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__ChallengeResponse = soap_get_ns1__ChallengeResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__ChallengeResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (_ChallengeReturn && soap_tmp_ns1__ChallengeResponse->_ChallengeReturn)
		*_ChallengeReturn = *soap_tmp_ns1__ChallengeResponse->_ChallengeReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__UserListGet(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_inStr, char **_UserListGetReturn)
{	struct ns1__UserListGet soap_tmp_ns1__UserListGet;
	struct ns1__UserListGetResponse *soap_tmp_ns1__UserListGetResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.30.202.81:8086/app/services/RNService";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp_ns1__UserListGet._inStr = _inStr;
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__UserListGet(soap, &soap_tmp_ns1__UserListGet);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__UserListGet(soap, &soap_tmp_ns1__UserListGet, "ns1:UserListGet", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__UserListGet(soap, &soap_tmp_ns1__UserListGet, "ns1:UserListGet", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_UserListGetReturn)
		return soap_closesock(soap);
	*_UserListGetReturn = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__UserListGetResponse = soap_get_ns1__UserListGetResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__UserListGetResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (_UserListGetReturn && soap_tmp_ns1__UserListGetResponse->_UserListGetReturn)
		*_UserListGetReturn = *soap_tmp_ns1__UserListGetResponse->_UserListGetReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getLocalHostIp(struct soap *soap, const char *soap_endpoint, const char *soap_action, char **getLocalHostIpReturn)
{	struct ns1__getLocalHostIp soap_tmp_ns1__getLocalHostIp;
	struct ns1__getLocalHostIpResponse *soap_tmp_ns1__getLocalHostIpResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.30.202.81:8086/app/services/RNService";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__getLocalHostIp(soap, &soap_tmp_ns1__getLocalHostIp);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getLocalHostIp(soap, &soap_tmp_ns1__getLocalHostIp, "ns1:getLocalHostIp", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getLocalHostIp(soap, &soap_tmp_ns1__getLocalHostIp, "ns1:getLocalHostIp", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!getLocalHostIpReturn)
		return soap_closesock(soap);
	*getLocalHostIpReturn = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__getLocalHostIpResponse = soap_get_ns1__getLocalHostIpResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__getLocalHostIpResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (getLocalHostIpReturn && soap_tmp_ns1__getLocalHostIpResponse->getLocalHostIpReturn)
		*getLocalHostIpReturn = *soap_tmp_ns1__getLocalHostIpResponse->getLocalHostIpReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__UserDefine(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_inStr, char **_UserDefineReturn)
{	struct ns1__UserDefine soap_tmp_ns1__UserDefine;
	struct ns1__UserDefineResponse *soap_tmp_ns1__UserDefineResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.30.202.81:8086/app/services/RNService";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp_ns1__UserDefine._inStr = _inStr;
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__UserDefine(soap, &soap_tmp_ns1__UserDefine);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__UserDefine(soap, &soap_tmp_ns1__UserDefine, "ns1:UserDefine", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__UserDefine(soap, &soap_tmp_ns1__UserDefine, "ns1:UserDefine", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_UserDefineReturn)
		return soap_closesock(soap);
	*_UserDefineReturn = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__UserDefineResponse = soap_get_ns1__UserDefineResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__UserDefineResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (_UserDefineReturn && soap_tmp_ns1__UserDefineResponse->_UserDefineReturn)
		*_UserDefineReturn = *soap_tmp_ns1__UserDefineResponse->_UserDefineReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__UserModify(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_inStr, char **_UserModifyReturn)
{	struct ns1__UserModify soap_tmp_ns1__UserModify;
	struct ns1__UserModifyResponse *soap_tmp_ns1__UserModifyResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.30.202.81:8086/app/services/RNService";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp_ns1__UserModify._inStr = _inStr;
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__UserModify(soap, &soap_tmp_ns1__UserModify);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__UserModify(soap, &soap_tmp_ns1__UserModify, "ns1:UserModify", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__UserModify(soap, &soap_tmp_ns1__UserModify, "ns1:UserModify", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_UserModifyReturn)
		return soap_closesock(soap);
	*_UserModifyReturn = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__UserModifyResponse = soap_get_ns1__UserModifyResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__UserModifyResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (_UserModifyReturn && soap_tmp_ns1__UserModifyResponse->_UserModifyReturn)
		*_UserModifyReturn = *soap_tmp_ns1__UserModifyResponse->_UserModifyReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__UserCancel(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_inStr, char **_UserCancelReturn)
{	struct ns1__UserCancel soap_tmp_ns1__UserCancel;
	struct ns1__UserCancelResponse *soap_tmp_ns1__UserCancelResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.30.202.81:8086/app/services/RNService";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp_ns1__UserCancel._inStr = _inStr;
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__UserCancel(soap, &soap_tmp_ns1__UserCancel);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__UserCancel(soap, &soap_tmp_ns1__UserCancel, "ns1:UserCancel", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__UserCancel(soap, &soap_tmp_ns1__UserCancel, "ns1:UserCancel", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_UserCancelReturn)
		return soap_closesock(soap);
	*_UserCancelReturn = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__UserCancelResponse = soap_get_ns1__UserCancelResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__UserCancelResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (_UserCancelReturn && soap_tmp_ns1__UserCancelResponse->_UserCancelReturn)
		*_UserCancelReturn = *soap_tmp_ns1__UserCancelResponse->_UserCancelReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__unitListGet(struct soap *soap, const char *soap_endpoint, const char *soap_action, char **unitListGetReturn)
{	struct ns1__unitListGet soap_tmp_ns1__unitListGet;
	struct ns1__unitListGetResponse *soap_tmp_ns1__unitListGetResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.30.202.81:8086/app/services/RNService";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__unitListGet(soap, &soap_tmp_ns1__unitListGet);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__unitListGet(soap, &soap_tmp_ns1__unitListGet, "ns1:unitListGet", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__unitListGet(soap, &soap_tmp_ns1__unitListGet, "ns1:unitListGet", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!unitListGetReturn)
		return soap_closesock(soap);
	*unitListGetReturn = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__unitListGetResponse = soap_get_ns1__unitListGetResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__unitListGetResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (unitListGetReturn && soap_tmp_ns1__unitListGetResponse->unitListGetReturn)
		*unitListGetReturn = *soap_tmp_ns1__unitListGetResponse->unitListGetReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__dicDataGet(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_type, char **_dicDataGetReturn)
{	struct ns1__dicDataGet soap_tmp_ns1__dicDataGet;
	struct ns1__dicDataGetResponse *soap_tmp_ns1__dicDataGetResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.30.202.81:8086/app/services/RNService";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp_ns1__dicDataGet._type = _type;
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__dicDataGet(soap, &soap_tmp_ns1__dicDataGet);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__dicDataGet(soap, &soap_tmp_ns1__dicDataGet, "ns1:dicDataGet", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__dicDataGet(soap, &soap_tmp_ns1__dicDataGet, "ns1:dicDataGet", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_dicDataGetReturn)
		return soap_closesock(soap);
	*_dicDataGetReturn = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__dicDataGetResponse = soap_get_ns1__dicDataGetResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__dicDataGetResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (_dicDataGetReturn && soap_tmp_ns1__dicDataGetResponse->_dicDataGetReturn)
		*_dicDataGetReturn = *soap_tmp_ns1__dicDataGetResponse->_dicDataGetReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__synAuthList(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ArrayOf_USCORExsd_USCOREanyType *_authList, struct ns1__synAuthListResponse *_param_1)
{	struct ns1__synAuthList soap_tmp_ns1__synAuthList;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.30.202.81:8086/app/services/RNService";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp_ns1__synAuthList._authList = _authList;
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__synAuthList(soap, &soap_tmp_ns1__synAuthList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__synAuthList(soap, &soap_tmp_ns1__synAuthList, "ns1:synAuthList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__synAuthList(soap, &soap_tmp_ns1__synAuthList, "ns1:synAuthList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_1)
		return soap_closesock(soap);
	soap_default_ns1__synAuthListResponse(soap, _param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__synAuthListResponse(soap, _param_1, "", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
