/* soapStub.h
   Generated by gSOAP 2.8.71 for res.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/


#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 20871
# error "GSOAP VERSION 20871 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Structs and Unions                                                         *
 *                                                                            *
\******************************************************************************/

struct ns1__addDeviceBatchResponse;	/* res.h:249 */
struct ns1__addDeviceBatch;	/* res.h:249 */
struct ns1__DeviceDefineResponse;	/* res.h:304 */
struct ns1__DeviceDefine;	/* res.h:304 */
struct ns1__SoftListGetResponse;	/* res.h:359 */
struct ns1__SoftListGet;	/* res.h:359 */
struct ns1__SoftDefineResponse;	/* res.h:414 */
struct ns1__SoftDefine;	/* res.h:414 */
struct ns1__ChallengeResponse;	/* res.h:469 */
struct ns1__Challenge;	/* res.h:469 */
struct ns1__DataListGetResponse;	/* res.h:524 */
struct ns1__DataListGet;	/* res.h:524 */
struct ns1__DataDefineResponse;	/* res.h:579 */
struct ns1__DataDefine;	/* res.h:579 */
struct ns1__DeviceCancelResponse;	/* res.h:634 */
struct ns1__DeviceCancel;	/* res.h:634 */
struct ns1__DeviceModifyResponse;	/* res.h:689 */
struct ns1__DeviceModify;	/* res.h:689 */
struct ns1__DeviceListGetResponse;	/* res.h:744 */
struct ns1__DeviceListGet;	/* res.h:744 */
struct ns1__SoftCancelResponse;	/* res.h:799 */
struct ns1__SoftCancel;	/* res.h:799 */
struct ns1__SoftModifyResponse;	/* res.h:854 */
struct ns1__SoftModify;	/* res.h:854 */
struct ns1__DataCancelResponse;	/* res.h:909 */
struct ns1__DataCancel;	/* res.h:909 */
struct ns1__DataModifyResponse;	/* res.h:964 */
struct ns1__DataModify;	/* res.h:964 */

/* res.h:249 */
#ifndef SOAP_TYPE_ns1__addDeviceBatchResponse
#define SOAP_TYPE_ns1__addDeviceBatchResponse (9)
/* complex XML schema type 'ns1:addDeviceBatchResponse': */
struct ns1__addDeviceBatchResponse {
        /** Optional element 'addDeviceBatchReturn' of XML schema type 'xsd:string' */
        char **addDeviceBatchReturn;
};
#endif

/* res.h:249 */
#ifndef SOAP_TYPE_ns1__addDeviceBatch
#define SOAP_TYPE_ns1__addDeviceBatch (10)
/* complex XML schema type 'ns1:addDeviceBatch': */
struct ns1__addDeviceBatch {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* res.h:304 */
#ifndef SOAP_TYPE_ns1__DeviceDefineResponse
#define SOAP_TYPE_ns1__DeviceDefineResponse (12)
/* complex XML schema type 'ns1:DeviceDefineResponse': */
struct ns1__DeviceDefineResponse {
        /** Optional element 'DeviceDefineReturn' of XML schema type 'xsd:string' */
        char **_DeviceDefineReturn;
};
#endif

/* res.h:304 */
#ifndef SOAP_TYPE_ns1__DeviceDefine
#define SOAP_TYPE_ns1__DeviceDefine (13)
/* complex XML schema type 'ns1:DeviceDefine': */
struct ns1__DeviceDefine {
        /** Optional element 'inStr' of XML schema type 'xsd:string' */
        char *_inStr;
};
#endif

/* res.h:359 */
#ifndef SOAP_TYPE_ns1__SoftListGetResponse
#define SOAP_TYPE_ns1__SoftListGetResponse (15)
/* complex XML schema type 'ns1:SoftListGetResponse': */
struct ns1__SoftListGetResponse {
        /** Optional element 'SoftListGetReturn' of XML schema type 'xsd:string' */
        char **_SoftListGetReturn;
};
#endif

/* res.h:359 */
#ifndef SOAP_TYPE_ns1__SoftListGet
#define SOAP_TYPE_ns1__SoftListGet (16)
/* complex XML schema type 'ns1:SoftListGet': */
struct ns1__SoftListGet {
        /** Optional element 'inStr' of XML schema type 'xsd:string' */
        char *_inStr;
};
#endif

/* res.h:414 */
#ifndef SOAP_TYPE_ns1__SoftDefineResponse
#define SOAP_TYPE_ns1__SoftDefineResponse (18)
/* complex XML schema type 'ns1:SoftDefineResponse': */
struct ns1__SoftDefineResponse {
        /** Optional element 'SoftDefineReturn' of XML schema type 'xsd:string' */
        char **_SoftDefineReturn;
};
#endif

/* res.h:414 */
#ifndef SOAP_TYPE_ns1__SoftDefine
#define SOAP_TYPE_ns1__SoftDefine (19)
/* complex XML schema type 'ns1:SoftDefine': */
struct ns1__SoftDefine {
        /** Optional element 'inStr' of XML schema type 'xsd:string' */
        char *_inStr;
};
#endif

/* res.h:469 */
#ifndef SOAP_TYPE_ns1__ChallengeResponse
#define SOAP_TYPE_ns1__ChallengeResponse (21)
/* complex XML schema type 'ns1:ChallengeResponse': */
struct ns1__ChallengeResponse {
        /** Optional element 'ChallengeReturn' of XML schema type 'xsd:string' */
        char **_ChallengeReturn;
};
#endif

/* res.h:469 */
#ifndef SOAP_TYPE_ns1__Challenge
#define SOAP_TYPE_ns1__Challenge (22)
/* complex XML schema type 'ns1:Challenge': */
struct ns1__Challenge {
        /** Optional element 'inStr' of XML schema type 'xsd:string' */
        char *_inStr;
};
#endif

/* res.h:524 */
#ifndef SOAP_TYPE_ns1__DataListGetResponse
#define SOAP_TYPE_ns1__DataListGetResponse (24)
/* complex XML schema type 'ns1:DataListGetResponse': */
struct ns1__DataListGetResponse {
        /** Optional element 'DataListGetReturn' of XML schema type 'xsd:string' */
        char **_DataListGetReturn;
};
#endif

/* res.h:524 */
#ifndef SOAP_TYPE_ns1__DataListGet
#define SOAP_TYPE_ns1__DataListGet (25)
/* complex XML schema type 'ns1:DataListGet': */
struct ns1__DataListGet {
        /** Optional element 'inStr' of XML schema type 'xsd:string' */
        char *_inStr;
};
#endif

/* res.h:579 */
#ifndef SOAP_TYPE_ns1__DataDefineResponse
#define SOAP_TYPE_ns1__DataDefineResponse (27)
/* complex XML schema type 'ns1:DataDefineResponse': */
struct ns1__DataDefineResponse {
        /** Optional element 'DataDefineReturn' of XML schema type 'xsd:string' */
        char **_DataDefineReturn;
};
#endif

/* res.h:579 */
#ifndef SOAP_TYPE_ns1__DataDefine
#define SOAP_TYPE_ns1__DataDefine (28)
/* complex XML schema type 'ns1:DataDefine': */
struct ns1__DataDefine {
        /** Optional element 'inStr' of XML schema type 'xsd:string' */
        char *_inStr;
};
#endif

/* res.h:634 */
#ifndef SOAP_TYPE_ns1__DeviceCancelResponse
#define SOAP_TYPE_ns1__DeviceCancelResponse (30)
/* complex XML schema type 'ns1:DeviceCancelResponse': */
struct ns1__DeviceCancelResponse {
        /** Optional element 'DeviceCancelReturn' of XML schema type 'xsd:string' */
        char **_DeviceCancelReturn;
};
#endif

/* res.h:634 */
#ifndef SOAP_TYPE_ns1__DeviceCancel
#define SOAP_TYPE_ns1__DeviceCancel (31)
/* complex XML schema type 'ns1:DeviceCancel': */
struct ns1__DeviceCancel {
        /** Optional element 'inStr' of XML schema type 'xsd:string' */
        char *_inStr;
};
#endif

/* res.h:689 */
#ifndef SOAP_TYPE_ns1__DeviceModifyResponse
#define SOAP_TYPE_ns1__DeviceModifyResponse (33)
/* complex XML schema type 'ns1:DeviceModifyResponse': */
struct ns1__DeviceModifyResponse {
        /** Optional element 'DeviceModifyReturn' of XML schema type 'xsd:string' */
        char **_DeviceModifyReturn;
};
#endif

/* res.h:689 */
#ifndef SOAP_TYPE_ns1__DeviceModify
#define SOAP_TYPE_ns1__DeviceModify (34)
/* complex XML schema type 'ns1:DeviceModify': */
struct ns1__DeviceModify {
        /** Optional element 'inStr' of XML schema type 'xsd:string' */
        char *_inStr;
};
#endif

/* res.h:744 */
#ifndef SOAP_TYPE_ns1__DeviceListGetResponse
#define SOAP_TYPE_ns1__DeviceListGetResponse (36)
/* complex XML schema type 'ns1:DeviceListGetResponse': */
struct ns1__DeviceListGetResponse {
        /** Optional element 'DeviceListGetReturn' of XML schema type 'xsd:string' */
        char **_DeviceListGetReturn;
};
#endif

/* res.h:744 */
#ifndef SOAP_TYPE_ns1__DeviceListGet
#define SOAP_TYPE_ns1__DeviceListGet (37)
/* complex XML schema type 'ns1:DeviceListGet': */
struct ns1__DeviceListGet {
        /** Optional element 'inStr' of XML schema type 'xsd:string' */
        char *_inStr;
};
#endif

/* res.h:799 */
#ifndef SOAP_TYPE_ns1__SoftCancelResponse
#define SOAP_TYPE_ns1__SoftCancelResponse (39)
/* complex XML schema type 'ns1:SoftCancelResponse': */
struct ns1__SoftCancelResponse {
        /** Optional element 'SoftCancelReturn' of XML schema type 'xsd:string' */
        char **_SoftCancelReturn;
};
#endif

/* res.h:799 */
#ifndef SOAP_TYPE_ns1__SoftCancel
#define SOAP_TYPE_ns1__SoftCancel (40)
/* complex XML schema type 'ns1:SoftCancel': */
struct ns1__SoftCancel {
        /** Optional element 'inStr' of XML schema type 'xsd:string' */
        char *_inStr;
};
#endif

/* res.h:854 */
#ifndef SOAP_TYPE_ns1__SoftModifyResponse
#define SOAP_TYPE_ns1__SoftModifyResponse (42)
/* complex XML schema type 'ns1:SoftModifyResponse': */
struct ns1__SoftModifyResponse {
        /** Optional element 'SoftModifyReturn' of XML schema type 'xsd:string' */
        char **_SoftModifyReturn;
};
#endif

/* res.h:854 */
#ifndef SOAP_TYPE_ns1__SoftModify
#define SOAP_TYPE_ns1__SoftModify (43)
/* complex XML schema type 'ns1:SoftModify': */
struct ns1__SoftModify {
        /** Optional element 'inStr' of XML schema type 'xsd:string' */
        char *_inStr;
};
#endif

/* res.h:909 */
#ifndef SOAP_TYPE_ns1__DataCancelResponse
#define SOAP_TYPE_ns1__DataCancelResponse (45)
/* complex XML schema type 'ns1:DataCancelResponse': */
struct ns1__DataCancelResponse {
        /** Optional element 'DataCancelReturn' of XML schema type 'xsd:string' */
        char **_DataCancelReturn;
};
#endif

/* res.h:909 */
#ifndef SOAP_TYPE_ns1__DataCancel
#define SOAP_TYPE_ns1__DataCancel (46)
/* complex XML schema type 'ns1:DataCancel': */
struct ns1__DataCancel {
        /** Optional element 'inStr' of XML schema type 'xsd:string' */
        char *_inStr;
};
#endif

/* res.h:964 */
#ifndef SOAP_TYPE_ns1__DataModifyResponse
#define SOAP_TYPE_ns1__DataModifyResponse (48)
/* complex XML schema type 'ns1:DataModifyResponse': */
struct ns1__DataModifyResponse {
        /** Optional element 'DataModifyReturn' of XML schema type 'xsd:string' */
        char **_DataModifyReturn;
};
#endif

/* res.h:964 */
#ifndef SOAP_TYPE_ns1__DataModify
#define SOAP_TYPE_ns1__DataModify (49)
/* complex XML schema type 'ns1:DataModify': */
struct ns1__DataModify {
        /** Optional element 'inStr' of XML schema type 'xsd:string' */
        char *_inStr;
};
#endif

/* res.h:977 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (50)
/* SOAP_ENV__Header: */
struct SOAP_ENV__Header {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif
#endif

/* res.h:977 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (51)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_ENV__Code {
        /** Optional element 'SOAP-ENV:Value' of XML schema type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
};
#endif
#endif

/* res.h:977 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (53)
/* SOAP_ENV__Detail: */
struct SOAP_ENV__Detail {
        char *__any;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_T assigned to __type */
        /** Do not create a cyclic data structure throught this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
};
#endif
#endif

/* res.h:977 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (56)
/* SOAP_ENV__Reason: */
struct SOAP_ENV__Reason {
        /** Optional element 'SOAP-ENV:Text' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Text;
};
#endif
#endif

/* res.h:977 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (57)
/* SOAP_ENV__Fault: */
struct SOAP_ENV__Fault {
        /** Optional element 'faultcode' of XML schema type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XML schema type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XML schema type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XML schema type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
};
#endif
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* (built-in):0 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
typedef char *_XML;
#endif

/* (built-in):0 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
typedef char *_QName;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (57)
#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (56)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (53)
#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (51)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (50)
#endif

/* struct ns1__DataModify has binding name 'ns1__DataModify' for type 'ns1:DataModify' */
#ifndef SOAP_TYPE_ns1__DataModify
#define SOAP_TYPE_ns1__DataModify (49)
#endif

/* struct ns1__DataModifyResponse has binding name 'ns1__DataModifyResponse' for type 'ns1:DataModifyResponse' */
#ifndef SOAP_TYPE_ns1__DataModifyResponse
#define SOAP_TYPE_ns1__DataModifyResponse (48)
#endif

/* struct ns1__DataCancel has binding name 'ns1__DataCancel' for type 'ns1:DataCancel' */
#ifndef SOAP_TYPE_ns1__DataCancel
#define SOAP_TYPE_ns1__DataCancel (46)
#endif

/* struct ns1__DataCancelResponse has binding name 'ns1__DataCancelResponse' for type 'ns1:DataCancelResponse' */
#ifndef SOAP_TYPE_ns1__DataCancelResponse
#define SOAP_TYPE_ns1__DataCancelResponse (45)
#endif

/* struct ns1__SoftModify has binding name 'ns1__SoftModify' for type 'ns1:SoftModify' */
#ifndef SOAP_TYPE_ns1__SoftModify
#define SOAP_TYPE_ns1__SoftModify (43)
#endif

/* struct ns1__SoftModifyResponse has binding name 'ns1__SoftModifyResponse' for type 'ns1:SoftModifyResponse' */
#ifndef SOAP_TYPE_ns1__SoftModifyResponse
#define SOAP_TYPE_ns1__SoftModifyResponse (42)
#endif

/* struct ns1__SoftCancel has binding name 'ns1__SoftCancel' for type 'ns1:SoftCancel' */
#ifndef SOAP_TYPE_ns1__SoftCancel
#define SOAP_TYPE_ns1__SoftCancel (40)
#endif

/* struct ns1__SoftCancelResponse has binding name 'ns1__SoftCancelResponse' for type 'ns1:SoftCancelResponse' */
#ifndef SOAP_TYPE_ns1__SoftCancelResponse
#define SOAP_TYPE_ns1__SoftCancelResponse (39)
#endif

/* struct ns1__DeviceListGet has binding name 'ns1__DeviceListGet' for type 'ns1:DeviceListGet' */
#ifndef SOAP_TYPE_ns1__DeviceListGet
#define SOAP_TYPE_ns1__DeviceListGet (37)
#endif

/* struct ns1__DeviceListGetResponse has binding name 'ns1__DeviceListGetResponse' for type 'ns1:DeviceListGetResponse' */
#ifndef SOAP_TYPE_ns1__DeviceListGetResponse
#define SOAP_TYPE_ns1__DeviceListGetResponse (36)
#endif

/* struct ns1__DeviceModify has binding name 'ns1__DeviceModify' for type 'ns1:DeviceModify' */
#ifndef SOAP_TYPE_ns1__DeviceModify
#define SOAP_TYPE_ns1__DeviceModify (34)
#endif

/* struct ns1__DeviceModifyResponse has binding name 'ns1__DeviceModifyResponse' for type 'ns1:DeviceModifyResponse' */
#ifndef SOAP_TYPE_ns1__DeviceModifyResponse
#define SOAP_TYPE_ns1__DeviceModifyResponse (33)
#endif

/* struct ns1__DeviceCancel has binding name 'ns1__DeviceCancel' for type 'ns1:DeviceCancel' */
#ifndef SOAP_TYPE_ns1__DeviceCancel
#define SOAP_TYPE_ns1__DeviceCancel (31)
#endif

/* struct ns1__DeviceCancelResponse has binding name 'ns1__DeviceCancelResponse' for type 'ns1:DeviceCancelResponse' */
#ifndef SOAP_TYPE_ns1__DeviceCancelResponse
#define SOAP_TYPE_ns1__DeviceCancelResponse (30)
#endif

/* struct ns1__DataDefine has binding name 'ns1__DataDefine' for type 'ns1:DataDefine' */
#ifndef SOAP_TYPE_ns1__DataDefine
#define SOAP_TYPE_ns1__DataDefine (28)
#endif

/* struct ns1__DataDefineResponse has binding name 'ns1__DataDefineResponse' for type 'ns1:DataDefineResponse' */
#ifndef SOAP_TYPE_ns1__DataDefineResponse
#define SOAP_TYPE_ns1__DataDefineResponse (27)
#endif

/* struct ns1__DataListGet has binding name 'ns1__DataListGet' for type 'ns1:DataListGet' */
#ifndef SOAP_TYPE_ns1__DataListGet
#define SOAP_TYPE_ns1__DataListGet (25)
#endif

/* struct ns1__DataListGetResponse has binding name 'ns1__DataListGetResponse' for type 'ns1:DataListGetResponse' */
#ifndef SOAP_TYPE_ns1__DataListGetResponse
#define SOAP_TYPE_ns1__DataListGetResponse (24)
#endif

/* struct ns1__Challenge has binding name 'ns1__Challenge' for type 'ns1:Challenge' */
#ifndef SOAP_TYPE_ns1__Challenge
#define SOAP_TYPE_ns1__Challenge (22)
#endif

/* struct ns1__ChallengeResponse has binding name 'ns1__ChallengeResponse' for type 'ns1:ChallengeResponse' */
#ifndef SOAP_TYPE_ns1__ChallengeResponse
#define SOAP_TYPE_ns1__ChallengeResponse (21)
#endif

/* struct ns1__SoftDefine has binding name 'ns1__SoftDefine' for type 'ns1:SoftDefine' */
#ifndef SOAP_TYPE_ns1__SoftDefine
#define SOAP_TYPE_ns1__SoftDefine (19)
#endif

/* struct ns1__SoftDefineResponse has binding name 'ns1__SoftDefineResponse' for type 'ns1:SoftDefineResponse' */
#ifndef SOAP_TYPE_ns1__SoftDefineResponse
#define SOAP_TYPE_ns1__SoftDefineResponse (18)
#endif

/* struct ns1__SoftListGet has binding name 'ns1__SoftListGet' for type 'ns1:SoftListGet' */
#ifndef SOAP_TYPE_ns1__SoftListGet
#define SOAP_TYPE_ns1__SoftListGet (16)
#endif

/* struct ns1__SoftListGetResponse has binding name 'ns1__SoftListGetResponse' for type 'ns1:SoftListGetResponse' */
#ifndef SOAP_TYPE_ns1__SoftListGetResponse
#define SOAP_TYPE_ns1__SoftListGetResponse (15)
#endif

/* struct ns1__DeviceDefine has binding name 'ns1__DeviceDefine' for type 'ns1:DeviceDefine' */
#ifndef SOAP_TYPE_ns1__DeviceDefine
#define SOAP_TYPE_ns1__DeviceDefine (13)
#endif

/* struct ns1__DeviceDefineResponse has binding name 'ns1__DeviceDefineResponse' for type 'ns1:DeviceDefineResponse' */
#ifndef SOAP_TYPE_ns1__DeviceDefineResponse
#define SOAP_TYPE_ns1__DeviceDefineResponse (12)
#endif

/* struct ns1__addDeviceBatch has binding name 'ns1__addDeviceBatch' for type 'ns1:addDeviceBatch' */
#ifndef SOAP_TYPE_ns1__addDeviceBatch
#define SOAP_TYPE_ns1__addDeviceBatch (10)
#endif

/* struct ns1__addDeviceBatchResponse has binding name 'ns1__addDeviceBatchResponse' for type 'ns1:addDeviceBatchResponse' */
#ifndef SOAP_TYPE_ns1__addDeviceBatchResponse
#define SOAP_TYPE_ns1__addDeviceBatchResponse (9)
#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (59)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (58)
#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (52)
#endif

/* char ** has binding name 'PointerTostring' for type 'xsd:string' */
#ifndef SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (7)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stub Functions                                            *
 *                                                                            *
\******************************************************************************/

    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__addDeviceBatch(struct soap *soap, const char *soap_endpoint, const char *soap_action, char **addDeviceBatchReturn);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__DeviceDefine(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_inStr, char **_DeviceDefineReturn);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__SoftListGet(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_inStr, char **_SoftListGetReturn);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__SoftDefine(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_inStr, char **_SoftDefineReturn);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__Challenge(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_inStr, char **_ChallengeReturn);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__DataListGet(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_inStr, char **_DataListGetReturn);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__DataDefine(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_inStr, char **_DataDefineReturn);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__DeviceCancel(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_inStr, char **_DeviceCancelReturn);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__DeviceModify(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_inStr, char **_DeviceModifyReturn);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__DeviceListGet(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_inStr, char **_DeviceListGetReturn);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__SoftCancel(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_inStr, char **_SoftCancelReturn);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__SoftModify(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_inStr, char **_SoftModifyReturn);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__DataCancel(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_inStr, char **_DataCancelReturn);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__DataModify(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_inStr, char **_DataModifyReturn);

/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/

    /** Web service operation 'ns1__addDeviceBatch' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__addDeviceBatch(struct soap*, char **addDeviceBatchReturn);
    /** Web service operation 'ns1__DeviceDefine' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__DeviceDefine(struct soap*, char *_inStr, char **_DeviceDefineReturn);
    /** Web service operation 'ns1__SoftListGet' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__SoftListGet(struct soap*, char *_inStr, char **_SoftListGetReturn);
    /** Web service operation 'ns1__SoftDefine' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__SoftDefine(struct soap*, char *_inStr, char **_SoftDefineReturn);
    /** Web service operation 'ns1__Challenge' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__Challenge(struct soap*, char *_inStr, char **_ChallengeReturn);
    /** Web service operation 'ns1__DataListGet' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__DataListGet(struct soap*, char *_inStr, char **_DataListGetReturn);
    /** Web service operation 'ns1__DataDefine' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__DataDefine(struct soap*, char *_inStr, char **_DataDefineReturn);
    /** Web service operation 'ns1__DeviceCancel' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__DeviceCancel(struct soap*, char *_inStr, char **_DeviceCancelReturn);
    /** Web service operation 'ns1__DeviceModify' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__DeviceModify(struct soap*, char *_inStr, char **_DeviceModifyReturn);
    /** Web service operation 'ns1__DeviceListGet' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__DeviceListGet(struct soap*, char *_inStr, char **_DeviceListGetReturn);
    /** Web service operation 'ns1__SoftCancel' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__SoftCancel(struct soap*, char *_inStr, char **_SoftCancelReturn);
    /** Web service operation 'ns1__SoftModify' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__SoftModify(struct soap*, char *_inStr, char **_SoftModifyReturn);
    /** Web service operation 'ns1__DataCancel' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__DataCancel(struct soap*, char *_inStr, char **_DataCancelReturn);
    /** Web service operation 'ns1__DataModify' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__DataModify(struct soap*, char *_inStr, char **_DataModifyReturn);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__addDeviceBatch(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__DeviceDefine(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__SoftListGet(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__SoftDefine(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__Challenge(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__DataListGet(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__DataDefine(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__DeviceCancel(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__DeviceModify(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__DeviceListGet(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__SoftCancel(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__SoftModify(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__DataCancel(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__DataModify(struct soap*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
