/* soapClient.c
   Generated by gSOAP 2.8.71 for soapH.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.71 2021-04-12 14:26:57 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__authSecAssert(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__authSecAssert *ns1__authSecAssert, struct ns1__authSecAssertResponse *ns1__authSecAssertResponse)
{	struct __ns1__authSecAssert soap_tmp___ns1__authSecAssert;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.24.227.34:8080/wserver_war/app/services/AuthService http://172.24.227.34:8080/wserver_war/app/services/RNService http://172.24.227.34:8080/wserver_war/app/ws/auth";
	if (soap_action == NULL)
		soap_action = "http://service.ws.cn/AuthServiceSoapBindingImpl/authSecAssertRequest";
	soap_tmp___ns1__authSecAssert.ns1__authSecAssert = ns1__authSecAssert;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__authSecAssert(soap, &soap_tmp___ns1__authSecAssert);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__authSecAssert(soap, &soap_tmp___ns1__authSecAssert, "-ns1:authSecAssert", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__authSecAssert(soap, &soap_tmp___ns1__authSecAssert, "-ns1:authSecAssert", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__authSecAssertResponse)
		return soap_closesock(soap);
	soap_default_ns1__authSecAssertResponse(soap, ns1__authSecAssertResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__authSecAssertResponse(soap, ns1__authSecAssertResponse, "ns1:authSecAssertResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getResult(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__getResult *ns1__getResult, struct ns1__getResultResponse *ns1__getResultResponse)
{	struct __ns1__getResult soap_tmp___ns1__getResult;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.24.227.34:8080/wserver_war/app/services/AuthService http://172.24.227.34:8080/wserver_war/app/services/RNService http://172.24.227.34:8080/wserver_war/app/ws/auth";
	if (soap_action == NULL)
		soap_action = "http://service.ws.cn/AuthServiceSoapBindingImpl/getResultRequest";
	soap_tmp___ns1__getResult.ns1__getResult = ns1__getResult;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__getResult(soap, &soap_tmp___ns1__getResult);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getResult(soap, &soap_tmp___ns1__getResult, "-ns1:getResult", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getResult(soap, &soap_tmp___ns1__getResult, "-ns1:getResult", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getResultResponse)
		return soap_closesock(soap);
	soap_default_ns1__getResultResponse(soap, ns1__getResultResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__getResultResponse(soap, ns1__getResultResponse, "ns1:getResultResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__random(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__random *ns1__random, struct ns1__randomResponse *ns1__randomResponse)
{	struct __ns1__random soap_tmp___ns1__random;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.24.227.34:8080/wserver_war/app/services/AuthService http://172.24.227.34:8080/wserver_war/app/services/RNService http://172.24.227.34:8080/wserver_war/app/ws/auth";
	if (soap_action == NULL)
		soap_action = "http://service.ws.cn/AuthServiceSoapBindingImpl/randomRequest";
	soap_tmp___ns1__random.ns1__random = ns1__random;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__random(soap, &soap_tmp___ns1__random);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__random(soap, &soap_tmp___ns1__random, "-ns1:random", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__random(soap, &soap_tmp___ns1__random, "-ns1:random", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__randomResponse)
		return soap_closesock(soap);
	soap_default_ns1__randomResponse(soap, ns1__randomResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__randomResponse(soap, ns1__randomResponse, "ns1:randomResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getPermissionById(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__getPermissionById *ns1__getPermissionById, struct ns1__getPermissionByIdResponse *ns1__getPermissionByIdResponse)
{	struct __ns1__getPermissionById soap_tmp___ns1__getPermissionById;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.24.227.34:8080/wserver_war/app/services/AuthService http://172.24.227.34:8080/wserver_war/app/services/RNService http://172.24.227.34:8080/wserver_war/app/ws/auth";
	if (soap_action == NULL)
		soap_action = "http://service.ws.cn/AuthorizeServiceSoapBindingImpl/getPermissionByIdRequest";
	soap_tmp___ns1__getPermissionById.ns1__getPermissionById = ns1__getPermissionById;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__getPermissionById(soap, &soap_tmp___ns1__getPermissionById);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getPermissionById(soap, &soap_tmp___ns1__getPermissionById, "-ns1:getPermissionById", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getPermissionById(soap, &soap_tmp___ns1__getPermissionById, "-ns1:getPermissionById", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getPermissionByIdResponse)
		return soap_closesock(soap);
	soap_default_ns1__getPermissionByIdResponse(soap, ns1__getPermissionByIdResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__getPermissionByIdResponse(soap, ns1__getPermissionByIdResponse, "ns1:getPermissionByIdResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__challenge(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__challenge *ns1__challenge, struct ns1__challengeResponse *ns1__challengeResponse)
{	struct __ns1__challenge soap_tmp___ns1__challenge;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.24.227.34:8080/wserver_war/app/services/AuthService http://172.24.227.34:8080/wserver_war/app/services/RNService http://172.24.227.34:8080/wserver_war/app/ws/auth";
	if (soap_action == NULL)
		soap_action = "http://service.ws.cn/AuthorizeServiceSoapBindingImpl/challengeRequest";
	soap_tmp___ns1__challenge.ns1__challenge = ns1__challenge;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__challenge(soap, &soap_tmp___ns1__challenge);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__challenge(soap, &soap_tmp___ns1__challenge, "-ns1:challenge", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__challenge(soap, &soap_tmp___ns1__challenge, "-ns1:challenge", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__challengeResponse)
		return soap_closesock(soap);
	soap_default_ns1__challengeResponse(soap, ns1__challengeResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__challengeResponse(soap, ns1__challengeResponse, "ns1:challengeResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getResult_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__getResult *ns1__getResult, struct ns1__getResultResponse *ns1__getResultResponse)
{	struct __ns1__getResult_ soap_tmp___ns1__getResult_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.24.227.34:8080/wserver_war/app/services/AuthService http://172.24.227.34:8080/wserver_war/app/services/RNService http://172.24.227.34:8080/wserver_war/app/ws/auth";
	if (soap_action == NULL)
		soap_action = "http://service.ws.cn/AuthorizeServiceSoapBindingImpl/getResultRequest";
	soap_tmp___ns1__getResult_.ns1__getResult = ns1__getResult;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__getResult_(soap, &soap_tmp___ns1__getResult_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getResult_(soap, &soap_tmp___ns1__getResult_, "-ns1:getResult", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getResult_(soap, &soap_tmp___ns1__getResult_, "-ns1:getResult", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getResultResponse)
		return soap_closesock(soap);
	soap_default_ns1__getResultResponse(soap, ns1__getResultResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__getResultResponse(soap, ns1__getResultResponse, "ns1:getResultResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__challenge_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__challenge *ns1__challenge, struct ns1__challengeResponse *ns1__challengeResponse)
{	struct __ns1__challenge_ soap_tmp___ns1__challenge_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.24.227.34:8080/wserver_war/app/services/AuthService http://172.24.227.34:8080/wserver_war/app/services/RNService http://172.24.227.34:8080/wserver_war/app/ws/auth";
	if (soap_action == NULL)
		soap_action = "http://service.ws.cn/RNServiceSoapBindingImpl/challengeRequest";
	soap_tmp___ns1__challenge_.ns1__challenge = ns1__challenge;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__challenge_(soap, &soap_tmp___ns1__challenge_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__challenge_(soap, &soap_tmp___ns1__challenge_, "-ns1:challenge", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__challenge_(soap, &soap_tmp___ns1__challenge_, "-ns1:challenge", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__challengeResponse)
		return soap_closesock(soap);
	soap_default_ns1__challengeResponse(soap, ns1__challengeResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__challengeResponse(soap, ns1__challengeResponse, "ns1:challengeResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__userVIDSet(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__userVIDSet *ns1__userVIDSet, struct ns1__userVIDSetResponse *ns1__userVIDSetResponse)
{	struct __ns1__userVIDSet soap_tmp___ns1__userVIDSet;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.24.227.34:8080/wserver_war/app/services/AuthService http://172.24.227.34:8080/wserver_war/app/services/RNService http://172.24.227.34:8080/wserver_war/app/ws/auth";
	if (soap_action == NULL)
		soap_action = "http://service.ws.cn/RNServiceSoapBindingImpl/userVIDSetRequest";
	soap_tmp___ns1__userVIDSet.ns1__userVIDSet = ns1__userVIDSet;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__userVIDSet(soap, &soap_tmp___ns1__userVIDSet);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__userVIDSet(soap, &soap_tmp___ns1__userVIDSet, "-ns1:userVIDSet", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__userVIDSet(soap, &soap_tmp___ns1__userVIDSet, "-ns1:userVIDSet", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__userVIDSetResponse)
		return soap_closesock(soap);
	soap_default_ns1__userVIDSetResponse(soap, ns1__userVIDSetResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__userVIDSetResponse(soap, ns1__userVIDSetResponse, "ns1:userVIDSetResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__userModify(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__userModify *ns1__userModify, struct ns1__userModifyResponse *ns1__userModifyResponse)
{	struct __ns1__userModify soap_tmp___ns1__userModify;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.24.227.34:8080/wserver_war/app/services/AuthService http://172.24.227.34:8080/wserver_war/app/services/RNService http://172.24.227.34:8080/wserver_war/app/ws/auth";
	if (soap_action == NULL)
		soap_action = "http://service.ws.cn/RNServiceSoapBindingImpl/userModifyRequest";
	soap_tmp___ns1__userModify.ns1__userModify = ns1__userModify;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__userModify(soap, &soap_tmp___ns1__userModify);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__userModify(soap, &soap_tmp___ns1__userModify, "-ns1:userModify", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__userModify(soap, &soap_tmp___ns1__userModify, "-ns1:userModify", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__userModifyResponse)
		return soap_closesock(soap);
	soap_default_ns1__userModifyResponse(soap, ns1__userModifyResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__userModifyResponse(soap, ns1__userModifyResponse, "ns1:userModifyResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__userRNCertGet(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__userRNCertGet *ns1__userRNCertGet, struct ns1__userRNCertGetResponse *ns1__userRNCertGetResponse)
{	struct __ns1__userRNCertGet soap_tmp___ns1__userRNCertGet;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.24.227.34:8080/wserver_war/app/services/AuthService http://172.24.227.34:8080/wserver_war/app/services/RNService http://172.24.227.34:8080/wserver_war/app/ws/auth";
	if (soap_action == NULL)
		soap_action = "http://service.ws.cn/RNServiceSoapBindingImpl/userRNCertGetRequest";
	soap_tmp___ns1__userRNCertGet.ns1__userRNCertGet = ns1__userRNCertGet;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__userRNCertGet(soap, &soap_tmp___ns1__userRNCertGet);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__userRNCertGet(soap, &soap_tmp___ns1__userRNCertGet, "-ns1:userRNCertGet", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__userRNCertGet(soap, &soap_tmp___ns1__userRNCertGet, "-ns1:userRNCertGet", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__userRNCertGetResponse)
		return soap_closesock(soap);
	soap_default_ns1__userRNCertGetResponse(soap, ns1__userRNCertGetResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__userRNCertGetResponse(soap, ns1__userRNCertGetResponse, "ns1:userRNCertGetResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__accessUnitGet(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__accessUnitGet *ns1__accessUnitGet, struct ns1__accessUnitGetResponse *ns1__accessUnitGetResponse)
{	struct __ns1__accessUnitGet soap_tmp___ns1__accessUnitGet;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.24.227.34:8080/wserver_war/app/services/AuthService http://172.24.227.34:8080/wserver_war/app/services/RNService http://172.24.227.34:8080/wserver_war/app/ws/auth";
	if (soap_action == NULL)
		soap_action = "http://service.ws.cn/RNServiceSoapBindingImpl/accessUnitGetRequest";
	soap_tmp___ns1__accessUnitGet.ns1__accessUnitGet = ns1__accessUnitGet;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__accessUnitGet(soap, &soap_tmp___ns1__accessUnitGet);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__accessUnitGet(soap, &soap_tmp___ns1__accessUnitGet, "-ns1:accessUnitGet", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__accessUnitGet(soap, &soap_tmp___ns1__accessUnitGet, "-ns1:accessUnitGet", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__accessUnitGetResponse)
		return soap_closesock(soap);
	soap_default_ns1__accessUnitGetResponse(soap, ns1__accessUnitGetResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__accessUnitGetResponse(soap, ns1__accessUnitGetResponse, "ns1:accessUnitGetResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__userCancel(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__userCancel *ns1__userCancel, struct ns1__userCancelResponse *ns1__userCancelResponse)
{	struct __ns1__userCancel soap_tmp___ns1__userCancel;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.24.227.34:8080/wserver_war/app/services/AuthService http://172.24.227.34:8080/wserver_war/app/services/RNService http://172.24.227.34:8080/wserver_war/app/ws/auth";
	if (soap_action == NULL)
		soap_action = "http://service.ws.cn/RNServiceSoapBindingImpl/userCancelRequest";
	soap_tmp___ns1__userCancel.ns1__userCancel = ns1__userCancel;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__userCancel(soap, &soap_tmp___ns1__userCancel);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__userCancel(soap, &soap_tmp___ns1__userCancel, "-ns1:userCancel", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__userCancel(soap, &soap_tmp___ns1__userCancel, "-ns1:userCancel", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__userCancelResponse)
		return soap_closesock(soap);
	soap_default_ns1__userCancelResponse(soap, ns1__userCancelResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__userCancelResponse(soap, ns1__userCancelResponse, "ns1:userCancelResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__verifyUserRN(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__verifyUserRN *ns1__verifyUserRN, struct ns1__verifyUserRNResponse *ns1__verifyUserRNResponse)
{	struct __ns1__verifyUserRN soap_tmp___ns1__verifyUserRN;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.24.227.34:8080/wserver_war/app/services/AuthService http://172.24.227.34:8080/wserver_war/app/services/RNService http://172.24.227.34:8080/wserver_war/app/ws/auth";
	if (soap_action == NULL)
		soap_action = "http://service.ws.cn/RNServiceSoapBindingImpl/verifyUserRNRequest";
	soap_tmp___ns1__verifyUserRN.ns1__verifyUserRN = ns1__verifyUserRN;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__verifyUserRN(soap, &soap_tmp___ns1__verifyUserRN);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__verifyUserRN(soap, &soap_tmp___ns1__verifyUserRN, "-ns1:verifyUserRN", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__verifyUserRN(soap, &soap_tmp___ns1__verifyUserRN, "-ns1:verifyUserRN", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__verifyUserRNResponse)
		return soap_closesock(soap);
	soap_default_ns1__verifyUserRNResponse(soap, ns1__verifyUserRNResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__verifyUserRNResponse(soap, ns1__verifyUserRNResponse, "ns1:verifyUserRNResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__userListGet(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__userListGet *ns1__userListGet, struct ns1__userListGetResponse *ns1__userListGetResponse)
{	struct __ns1__userListGet soap_tmp___ns1__userListGet;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.24.227.34:8080/wserver_war/app/services/AuthService http://172.24.227.34:8080/wserver_war/app/services/RNService http://172.24.227.34:8080/wserver_war/app/ws/auth";
	if (soap_action == NULL)
		soap_action = "http://service.ws.cn/RNServiceSoapBindingImpl/userListGetRequest";
	soap_tmp___ns1__userListGet.ns1__userListGet = ns1__userListGet;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__userListGet(soap, &soap_tmp___ns1__userListGet);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__userListGet(soap, &soap_tmp___ns1__userListGet, "-ns1:userListGet", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__userListGet(soap, &soap_tmp___ns1__userListGet, "-ns1:userListGet", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__userListGetResponse)
		return soap_closesock(soap);
	soap_default_ns1__userListGetResponse(soap, ns1__userListGetResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__userListGetResponse(soap, ns1__userListGetResponse, "ns1:userListGetResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__userDefine(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__userDefine *ns1__userDefine, struct ns1__userDefineResponse *ns1__userDefineResponse)
{	struct __ns1__userDefine soap_tmp___ns1__userDefine;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.24.227.34:8080/wserver_war/app/services/AuthService http://172.24.227.34:8080/wserver_war/app/services/RNService http://172.24.227.34:8080/wserver_war/app/ws/auth";
	if (soap_action == NULL)
		soap_action = "http://service.ws.cn/RNServiceSoapBindingImpl/userDefineRequest";
	soap_tmp___ns1__userDefine.ns1__userDefine = ns1__userDefine;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__userDefine(soap, &soap_tmp___ns1__userDefine);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__userDefine(soap, &soap_tmp___ns1__userDefine, "-ns1:userDefine", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__userDefine(soap, &soap_tmp___ns1__userDefine, "-ns1:userDefine", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__userDefineResponse)
		return soap_closesock(soap);
	soap_default_ns1__userDefineResponse(soap, ns1__userDefineResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__userDefineResponse(soap, ns1__userDefineResponse, "ns1:userDefineResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getResult__(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__getResult *ns1__getResult, struct ns1__getResultResponse *ns1__getResultResponse)
{	struct __ns1__getResult__ soap_tmp___ns1__getResult__;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://172.24.227.34:8080/wserver_war/app/services/AuthService http://172.24.227.34:8080/wserver_war/app/services/RNService http://172.24.227.34:8080/wserver_war/app/ws/auth";
	if (soap_action == NULL)
		soap_action = "http://service.ws.cn/RNServiceSoapBindingImpl/getResultRequest";
	soap_tmp___ns1__getResult__.ns1__getResult = ns1__getResult;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__getResult__(soap, &soap_tmp___ns1__getResult__);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getResult__(soap, &soap_tmp___ns1__getResult__, "-ns1:getResult", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getResult__(soap, &soap_tmp___ns1__getResult__, "-ns1:getResult", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getResultResponse)
		return soap_closesock(soap);
	soap_default_ns1__getResultResponse(soap, ns1__getResultResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__getResultResponse(soap, ns1__getResultResponse, "ns1:getResultResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
