/* soapStub.h
   Generated by gSOAP 2.8.71 for soapH.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#define SOAP_NAMESPACE_OF_ns1	"http://service.ws.cn/"

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 20871
# error "GSOAP VERSION 20871 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Structs and Unions                                                         *
 *                                                                            *
\******************************************************************************/

struct ns1__authSecAssert;	/* soapH.h:172 */
struct ns1__authSecAssertResponse;	/* soapH.h:187 */
struct ns1__random;	/* soapH.h:202 */
struct ns1__randomResponse;	/* soapH.h:215 */
struct ns1__getResult;	/* soapH.h:230 */
struct ns1__getResultResponse;	/* soapH.h:249 */
struct ns1__getPermissionById;	/* soapH.h:264 */
struct ns1__getPermissionByIdResponse;	/* soapH.h:279 */
struct ns1__challenge;	/* soapH.h:294 */
struct ns1__challengeResponse;	/* soapH.h:309 */
struct ns1__userModify;	/* soapH.h:324 */
struct ns1__userModifyResponse;	/* soapH.h:339 */
struct ns1__userVIDSet;	/* soapH.h:354 */
struct ns1__userVIDSetResponse;	/* soapH.h:369 */
struct ns1__verifyUserRN;	/* soapH.h:384 */
struct ns1__verifyUserRNResponse;	/* soapH.h:399 */
struct ns1__userCancel;	/* soapH.h:414 */
struct ns1__userCancelResponse;	/* soapH.h:429 */
struct ns1__accessUnitGet;	/* soapH.h:444 */
struct ns1__accessUnitGetResponse;	/* soapH.h:459 */
struct ns1__userDefine;	/* soapH.h:474 */
struct ns1__userDefineResponse;	/* soapH.h:489 */
struct ns1__userRNCertGet;	/* soapH.h:504 */
struct ns1__userRNCertGetResponse;	/* soapH.h:519 */
struct ns1__userListGet;	/* soapH.h:534 */
struct ns1__userListGetResponse;	/* soapH.h:549 */
struct __ns1__authSecAssert;	/* soapH.h:813 */
struct __ns1__getResult;	/* soapH.h:870 */
struct __ns1__random;	/* soapH.h:927 */
struct __ns1__getPermissionById;	/* soapH.h:984 */
struct __ns1__challenge;	/* soapH.h:1041 */
struct __ns1__getResult_;	/* soapH.h:1098 */
struct __ns1__challenge_;	/* soapH.h:1155 */
struct __ns1__userVIDSet;	/* soapH.h:1212 */
struct __ns1__userModify;	/* soapH.h:1269 */
struct __ns1__userRNCertGet;	/* soapH.h:1326 */
struct __ns1__accessUnitGet;	/* soapH.h:1383 */
struct __ns1__userCancel;	/* soapH.h:1440 */
struct __ns1__verifyUserRN;	/* soapH.h:1497 */
struct __ns1__userListGet;	/* soapH.h:1554 */
struct __ns1__userDefine;	/* soapH.h:1611 */
struct __ns1__getResult__;	/* soapH.h:1668 */

/* soapH.h:172 */
#ifndef SOAP_TYPE_ns1__authSecAssert
#define SOAP_TYPE_ns1__authSecAssert (7)
/* complex XML schema type 'ns1:authSecAssert': */
struct ns1__authSecAssert {
        /** Optional element 'arg0' of XML schema type 'xsd:string' */
        char *arg0;
};
#endif

/* soapH.h:187 */
#ifndef SOAP_TYPE_ns1__authSecAssertResponse
#define SOAP_TYPE_ns1__authSecAssertResponse (8)
/* complex XML schema type 'ns1:authSecAssertResponse': */
struct ns1__authSecAssertResponse {
        /** Optional element 'return' of XML schema type 'xsd:string' */
        char *return_;
};
#endif

/* soapH.h:202 */
#ifndef SOAP_TYPE_ns1__random
#define SOAP_TYPE_ns1__random (9)
/* complex XML schema type 'ns1:random': */
struct ns1__random {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* soapH.h:215 */
#ifndef SOAP_TYPE_ns1__randomResponse
#define SOAP_TYPE_ns1__randomResponse (10)
/* complex XML schema type 'ns1:randomResponse': */
struct ns1__randomResponse {
        /** Optional element 'return' of XML schema type 'xsd:string' */
        char *return_;
};
#endif

/* soapH.h:230 */
#ifndef SOAP_TYPE_ns1__getResult
#define SOAP_TYPE_ns1__getResult (11)
/* complex XML schema type 'ns1:getResult': */
struct ns1__getResult {
        /** Optional element 'arg0' of XML schema type 'xsd:string' */
        char *arg0;
        /** Optional element 'arg1' of XML schema type 'xsd:string' */
        char *arg1;
        /** Optional element 'arg2' of XML schema type 'xsd:string' */
        char *arg2;
};
#endif

/* soapH.h:249 */
#ifndef SOAP_TYPE_ns1__getResultResponse
#define SOAP_TYPE_ns1__getResultResponse (12)
/* complex XML schema type 'ns1:getResultResponse': */
struct ns1__getResultResponse {
        /** Optional element 'return' of XML schema type 'xsd:string' */
        char *return_;
};
#endif

/* soapH.h:264 */
#ifndef SOAP_TYPE_ns1__getPermissionById
#define SOAP_TYPE_ns1__getPermissionById (13)
/* complex XML schema type 'ns1:getPermissionById': */
struct ns1__getPermissionById {
        /** Optional element 'arg0' of XML schema type 'xsd:string' */
        char *arg0;
};
#endif

/* soapH.h:279 */
#ifndef SOAP_TYPE_ns1__getPermissionByIdResponse
#define SOAP_TYPE_ns1__getPermissionByIdResponse (14)
/* complex XML schema type 'ns1:getPermissionByIdResponse': */
struct ns1__getPermissionByIdResponse {
        /** Optional element 'return' of XML schema type 'xsd:string' */
        char *return_;
};
#endif

/* soapH.h:294 */
#ifndef SOAP_TYPE_ns1__challenge
#define SOAP_TYPE_ns1__challenge (15)
/* complex XML schema type 'ns1:challenge': */
struct ns1__challenge {
        /** Optional element 'arg0' of XML schema type 'xsd:string' */
        char *arg0;
};
#endif

/* soapH.h:309 */
#ifndef SOAP_TYPE_ns1__challengeResponse
#define SOAP_TYPE_ns1__challengeResponse (16)
/* complex XML schema type 'ns1:challengeResponse': */
struct ns1__challengeResponse {
        /** Optional element 'return' of XML schema type 'xsd:string' */
        char *return_;
};
#endif

/* soapH.h:324 */
#ifndef SOAP_TYPE_ns1__userModify
#define SOAP_TYPE_ns1__userModify (17)
/* complex XML schema type 'ns1:userModify': */
struct ns1__userModify {
        /** Optional element 'arg0' of XML schema type 'xsd:string' */
        char *arg0;
};
#endif

/* soapH.h:339 */
#ifndef SOAP_TYPE_ns1__userModifyResponse
#define SOAP_TYPE_ns1__userModifyResponse (18)
/* complex XML schema type 'ns1:userModifyResponse': */
struct ns1__userModifyResponse {
        /** Optional element 'return' of XML schema type 'xsd:string' */
        char *return_;
};
#endif

/* soapH.h:354 */
#ifndef SOAP_TYPE_ns1__userVIDSet
#define SOAP_TYPE_ns1__userVIDSet (19)
/* complex XML schema type 'ns1:userVIDSet': */
struct ns1__userVIDSet {
        /** Optional element 'arg0' of XML schema type 'xsd:string' */
        char *arg0;
};
#endif

/* soapH.h:369 */
#ifndef SOAP_TYPE_ns1__userVIDSetResponse
#define SOAP_TYPE_ns1__userVIDSetResponse (20)
/* complex XML schema type 'ns1:userVIDSetResponse': */
struct ns1__userVIDSetResponse {
        /** Optional element 'return' of XML schema type 'xsd:string' */
        char *return_;
};
#endif

/* soapH.h:384 */
#ifndef SOAP_TYPE_ns1__verifyUserRN
#define SOAP_TYPE_ns1__verifyUserRN (21)
/* complex XML schema type 'ns1:verifyUserRN': */
struct ns1__verifyUserRN {
        /** Optional element 'arg0' of XML schema type 'xsd:string' */
        char *arg0;
};
#endif

/* soapH.h:399 */
#ifndef SOAP_TYPE_ns1__verifyUserRNResponse
#define SOAP_TYPE_ns1__verifyUserRNResponse (22)
/* complex XML schema type 'ns1:verifyUserRNResponse': */
struct ns1__verifyUserRNResponse {
        /** Optional element 'return' of XML schema type 'xsd:string' */
        char *return_;
};
#endif

/* soapH.h:414 */
#ifndef SOAP_TYPE_ns1__userCancel
#define SOAP_TYPE_ns1__userCancel (23)
/* complex XML schema type 'ns1:userCancel': */
struct ns1__userCancel {
        /** Optional element 'arg0' of XML schema type 'xsd:string' */
        char *arg0;
};
#endif

/* soapH.h:429 */
#ifndef SOAP_TYPE_ns1__userCancelResponse
#define SOAP_TYPE_ns1__userCancelResponse (24)
/* complex XML schema type 'ns1:userCancelResponse': */
struct ns1__userCancelResponse {
        /** Optional element 'return' of XML schema type 'xsd:string' */
        char *return_;
};
#endif

/* soapH.h:444 */
#ifndef SOAP_TYPE_ns1__accessUnitGet
#define SOAP_TYPE_ns1__accessUnitGet (25)
/* complex XML schema type 'ns1:accessUnitGet': */
struct ns1__accessUnitGet {
        /** Optional element 'arg0' of XML schema type 'xsd:string' */
        char *arg0;
};
#endif

/* soapH.h:459 */
#ifndef SOAP_TYPE_ns1__accessUnitGetResponse
#define SOAP_TYPE_ns1__accessUnitGetResponse (26)
/* complex XML schema type 'ns1:accessUnitGetResponse': */
struct ns1__accessUnitGetResponse {
        /** Optional element 'return' of XML schema type 'xsd:string' */
        char *return_;
};
#endif

/* soapH.h:474 */
#ifndef SOAP_TYPE_ns1__userDefine
#define SOAP_TYPE_ns1__userDefine (27)
/* complex XML schema type 'ns1:userDefine': */
struct ns1__userDefine {
        /** Optional element 'arg0' of XML schema type 'xsd:string' */
        char *arg0;
};
#endif

/* soapH.h:489 */
#ifndef SOAP_TYPE_ns1__userDefineResponse
#define SOAP_TYPE_ns1__userDefineResponse (28)
/* complex XML schema type 'ns1:userDefineResponse': */
struct ns1__userDefineResponse {
        /** Optional element 'return' of XML schema type 'xsd:string' */
        char *return_;
};
#endif

/* soapH.h:504 */
#ifndef SOAP_TYPE_ns1__userRNCertGet
#define SOAP_TYPE_ns1__userRNCertGet (29)
/* complex XML schema type 'ns1:userRNCertGet': */
struct ns1__userRNCertGet {
        /** Optional element 'arg0' of XML schema type 'xsd:string' */
        char *arg0;
};
#endif

/* soapH.h:519 */
#ifndef SOAP_TYPE_ns1__userRNCertGetResponse
#define SOAP_TYPE_ns1__userRNCertGetResponse (30)
/* complex XML schema type 'ns1:userRNCertGetResponse': */
struct ns1__userRNCertGetResponse {
        /** Optional element 'return' of XML schema type 'xsd:string' */
        char *return_;
};
#endif

/* soapH.h:534 */
#ifndef SOAP_TYPE_ns1__userListGet
#define SOAP_TYPE_ns1__userListGet (31)
/* complex XML schema type 'ns1:userListGet': */
struct ns1__userListGet {
        /** Optional element 'arg0' of XML schema type 'xsd:string' */
        char *arg0;
};
#endif

/* soapH.h:549 */
#ifndef SOAP_TYPE_ns1__userListGetResponse
#define SOAP_TYPE_ns1__userListGetResponse (32)
/* complex XML schema type 'ns1:userListGetResponse': */
struct ns1__userListGetResponse {
        /** Optional element 'return' of XML schema type 'xsd:string' */
        char *return_;
};
#endif

/* soapH.h:813 */
#ifndef SOAP_TYPE___ns1__authSecAssert
#define SOAP_TYPE___ns1__authSecAssert (36)
/* Wrapper: */
struct __ns1__authSecAssert {
        /** Optional element 'ns1:authSecAssert' of XML schema type 'ns1:authSecAssert' */
        struct ns1__authSecAssert *ns1__authSecAssert;
};
#endif

/* soapH.h:870 */
#ifndef SOAP_TYPE___ns1__getResult
#define SOAP_TYPE___ns1__getResult (40)
/* Wrapper: */
struct __ns1__getResult {
        /** Optional element 'ns1:getResult' of XML schema type 'ns1:getResult' */
        struct ns1__getResult *ns1__getResult;
};
#endif

/* soapH.h:927 */
#ifndef SOAP_TYPE___ns1__random
#define SOAP_TYPE___ns1__random (44)
/* Wrapper: */
struct __ns1__random {
        /** Optional element 'ns1:random' of XML schema type 'ns1:random' */
        struct ns1__random *ns1__random;
};
#endif

/* soapH.h:984 */
#ifndef SOAP_TYPE___ns1__getPermissionById
#define SOAP_TYPE___ns1__getPermissionById (48)
/* Wrapper: */
struct __ns1__getPermissionById {
        /** Optional element 'ns1:getPermissionById' of XML schema type 'ns1:getPermissionById' */
        struct ns1__getPermissionById *ns1__getPermissionById;
};
#endif

/* soapH.h:1041 */
#ifndef SOAP_TYPE___ns1__challenge
#define SOAP_TYPE___ns1__challenge (52)
/* Wrapper: */
struct __ns1__challenge {
        /** Optional element 'ns1:challenge' of XML schema type 'ns1:challenge' */
        struct ns1__challenge *ns1__challenge;
};
#endif

/* soapH.h:1098 */
#ifndef SOAP_TYPE___ns1__getResult_
#define SOAP_TYPE___ns1__getResult_ (54)
/* Wrapper: */
struct __ns1__getResult_ {
        /** Optional element 'ns1:getResult' of XML schema type 'ns1:getResult' */
        struct ns1__getResult *ns1__getResult;
};
#endif

/* soapH.h:1155 */
#ifndef SOAP_TYPE___ns1__challenge_
#define SOAP_TYPE___ns1__challenge_ (56)
/* Wrapper: */
struct __ns1__challenge_ {
        /** Optional element 'ns1:challenge' of XML schema type 'ns1:challenge' */
        struct ns1__challenge *ns1__challenge;
};
#endif

/* soapH.h:1212 */
#ifndef SOAP_TYPE___ns1__userVIDSet
#define SOAP_TYPE___ns1__userVIDSet (60)
/* Wrapper: */
struct __ns1__userVIDSet {
        /** Optional element 'ns1:userVIDSet' of XML schema type 'ns1:userVIDSet' */
        struct ns1__userVIDSet *ns1__userVIDSet;
};
#endif

/* soapH.h:1269 */
#ifndef SOAP_TYPE___ns1__userModify
#define SOAP_TYPE___ns1__userModify (64)
/* Wrapper: */
struct __ns1__userModify {
        /** Optional element 'ns1:userModify' of XML schema type 'ns1:userModify' */
        struct ns1__userModify *ns1__userModify;
};
#endif

/* soapH.h:1326 */
#ifndef SOAP_TYPE___ns1__userRNCertGet
#define SOAP_TYPE___ns1__userRNCertGet (68)
/* Wrapper: */
struct __ns1__userRNCertGet {
        /** Optional element 'ns1:userRNCertGet' of XML schema type 'ns1:userRNCertGet' */
        struct ns1__userRNCertGet *ns1__userRNCertGet;
};
#endif

/* soapH.h:1383 */
#ifndef SOAP_TYPE___ns1__accessUnitGet
#define SOAP_TYPE___ns1__accessUnitGet (72)
/* Wrapper: */
struct __ns1__accessUnitGet {
        /** Optional element 'ns1:accessUnitGet' of XML schema type 'ns1:accessUnitGet' */
        struct ns1__accessUnitGet *ns1__accessUnitGet;
};
#endif

/* soapH.h:1440 */
#ifndef SOAP_TYPE___ns1__userCancel
#define SOAP_TYPE___ns1__userCancel (76)
/* Wrapper: */
struct __ns1__userCancel {
        /** Optional element 'ns1:userCancel' of XML schema type 'ns1:userCancel' */
        struct ns1__userCancel *ns1__userCancel;
};
#endif

/* soapH.h:1497 */
#ifndef SOAP_TYPE___ns1__verifyUserRN
#define SOAP_TYPE___ns1__verifyUserRN (80)
/* Wrapper: */
struct __ns1__verifyUserRN {
        /** Optional element 'ns1:verifyUserRN' of XML schema type 'ns1:verifyUserRN' */
        struct ns1__verifyUserRN *ns1__verifyUserRN;
};
#endif

/* soapH.h:1554 */
#ifndef SOAP_TYPE___ns1__userListGet
#define SOAP_TYPE___ns1__userListGet (84)
/* Wrapper: */
struct __ns1__userListGet {
        /** Optional element 'ns1:userListGet' of XML schema type 'ns1:userListGet' */
        struct ns1__userListGet *ns1__userListGet;
};
#endif

/* soapH.h:1611 */
#ifndef SOAP_TYPE___ns1__userDefine
#define SOAP_TYPE___ns1__userDefine (88)
/* Wrapper: */
struct __ns1__userDefine {
        /** Optional element 'ns1:userDefine' of XML schema type 'ns1:userDefine' */
        struct ns1__userDefine *ns1__userDefine;
};
#endif

/* soapH.h:1668 */
#ifndef SOAP_TYPE___ns1__getResult__
#define SOAP_TYPE___ns1__getResult__ (90)
/* Wrapper: */
struct __ns1__getResult__ {
        /** Optional element 'ns1:getResult' of XML schema type 'ns1:getResult' */
        struct ns1__getResult *ns1__getResult;
};
#endif

/* soapH.h:1783 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (91)
/* SOAP_ENV__Header: */
struct SOAP_ENV__Header {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif
#endif

/* soapH.h:1783 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (92)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_ENV__Code {
        /** Optional element 'SOAP-ENV:Value' of XML schema type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
};
#endif
#endif

/* soapH.h:1783 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (94)
/* SOAP_ENV__Detail: */
struct SOAP_ENV__Detail {
        char *__any;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_T assigned to __type */
        /** Do not create a cyclic data structure throught this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
};
#endif
#endif

/* soapH.h:1783 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (97)
/* SOAP_ENV__Reason: */
struct SOAP_ENV__Reason {
        /** Optional element 'SOAP-ENV:Text' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Text;
};
#endif
#endif

/* soapH.h:1783 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (98)
/* SOAP_ENV__Fault: */
struct SOAP_ENV__Fault {
        /** Optional element 'faultcode' of XML schema type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XML schema type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XML schema type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XML schema type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
};
#endif
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* (built-in):0 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
typedef char *_XML;
#endif

/* (built-in):0 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
typedef char *_QName;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (98)
#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (97)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (94)
#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (92)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (91)
#endif

/* struct ns1__userListGetResponse has binding name 'ns1__userListGetResponse' for type 'ns1:userListGetResponse' */
#ifndef SOAP_TYPE_ns1__userListGetResponse
#define SOAP_TYPE_ns1__userListGetResponse (32)
#endif

/* struct ns1__userListGet has binding name 'ns1__userListGet' for type 'ns1:userListGet' */
#ifndef SOAP_TYPE_ns1__userListGet
#define SOAP_TYPE_ns1__userListGet (31)
#endif

/* struct ns1__userRNCertGetResponse has binding name 'ns1__userRNCertGetResponse' for type 'ns1:userRNCertGetResponse' */
#ifndef SOAP_TYPE_ns1__userRNCertGetResponse
#define SOAP_TYPE_ns1__userRNCertGetResponse (30)
#endif

/* struct ns1__userRNCertGet has binding name 'ns1__userRNCertGet' for type 'ns1:userRNCertGet' */
#ifndef SOAP_TYPE_ns1__userRNCertGet
#define SOAP_TYPE_ns1__userRNCertGet (29)
#endif

/* struct ns1__userDefineResponse has binding name 'ns1__userDefineResponse' for type 'ns1:userDefineResponse' */
#ifndef SOAP_TYPE_ns1__userDefineResponse
#define SOAP_TYPE_ns1__userDefineResponse (28)
#endif

/* struct ns1__userDefine has binding name 'ns1__userDefine' for type 'ns1:userDefine' */
#ifndef SOAP_TYPE_ns1__userDefine
#define SOAP_TYPE_ns1__userDefine (27)
#endif

/* struct ns1__accessUnitGetResponse has binding name 'ns1__accessUnitGetResponse' for type 'ns1:accessUnitGetResponse' */
#ifndef SOAP_TYPE_ns1__accessUnitGetResponse
#define SOAP_TYPE_ns1__accessUnitGetResponse (26)
#endif

/* struct ns1__accessUnitGet has binding name 'ns1__accessUnitGet' for type 'ns1:accessUnitGet' */
#ifndef SOAP_TYPE_ns1__accessUnitGet
#define SOAP_TYPE_ns1__accessUnitGet (25)
#endif

/* struct ns1__userCancelResponse has binding name 'ns1__userCancelResponse' for type 'ns1:userCancelResponse' */
#ifndef SOAP_TYPE_ns1__userCancelResponse
#define SOAP_TYPE_ns1__userCancelResponse (24)
#endif

/* struct ns1__userCancel has binding name 'ns1__userCancel' for type 'ns1:userCancel' */
#ifndef SOAP_TYPE_ns1__userCancel
#define SOAP_TYPE_ns1__userCancel (23)
#endif

/* struct ns1__verifyUserRNResponse has binding name 'ns1__verifyUserRNResponse' for type 'ns1:verifyUserRNResponse' */
#ifndef SOAP_TYPE_ns1__verifyUserRNResponse
#define SOAP_TYPE_ns1__verifyUserRNResponse (22)
#endif

/* struct ns1__verifyUserRN has binding name 'ns1__verifyUserRN' for type 'ns1:verifyUserRN' */
#ifndef SOAP_TYPE_ns1__verifyUserRN
#define SOAP_TYPE_ns1__verifyUserRN (21)
#endif

/* struct ns1__userVIDSetResponse has binding name 'ns1__userVIDSetResponse' for type 'ns1:userVIDSetResponse' */
#ifndef SOAP_TYPE_ns1__userVIDSetResponse
#define SOAP_TYPE_ns1__userVIDSetResponse (20)
#endif

/* struct ns1__userVIDSet has binding name 'ns1__userVIDSet' for type 'ns1:userVIDSet' */
#ifndef SOAP_TYPE_ns1__userVIDSet
#define SOAP_TYPE_ns1__userVIDSet (19)
#endif

/* struct ns1__userModifyResponse has binding name 'ns1__userModifyResponse' for type 'ns1:userModifyResponse' */
#ifndef SOAP_TYPE_ns1__userModifyResponse
#define SOAP_TYPE_ns1__userModifyResponse (18)
#endif

/* struct ns1__userModify has binding name 'ns1__userModify' for type 'ns1:userModify' */
#ifndef SOAP_TYPE_ns1__userModify
#define SOAP_TYPE_ns1__userModify (17)
#endif

/* struct ns1__challengeResponse has binding name 'ns1__challengeResponse' for type 'ns1:challengeResponse' */
#ifndef SOAP_TYPE_ns1__challengeResponse
#define SOAP_TYPE_ns1__challengeResponse (16)
#endif

/* struct ns1__challenge has binding name 'ns1__challenge' for type 'ns1:challenge' */
#ifndef SOAP_TYPE_ns1__challenge
#define SOAP_TYPE_ns1__challenge (15)
#endif

/* struct ns1__getPermissionByIdResponse has binding name 'ns1__getPermissionByIdResponse' for type 'ns1:getPermissionByIdResponse' */
#ifndef SOAP_TYPE_ns1__getPermissionByIdResponse
#define SOAP_TYPE_ns1__getPermissionByIdResponse (14)
#endif

/* struct ns1__getPermissionById has binding name 'ns1__getPermissionById' for type 'ns1:getPermissionById' */
#ifndef SOAP_TYPE_ns1__getPermissionById
#define SOAP_TYPE_ns1__getPermissionById (13)
#endif

/* struct ns1__getResultResponse has binding name 'ns1__getResultResponse' for type 'ns1:getResultResponse' */
#ifndef SOAP_TYPE_ns1__getResultResponse
#define SOAP_TYPE_ns1__getResultResponse (12)
#endif

/* struct ns1__getResult has binding name 'ns1__getResult' for type 'ns1:getResult' */
#ifndef SOAP_TYPE_ns1__getResult
#define SOAP_TYPE_ns1__getResult (11)
#endif

/* struct ns1__randomResponse has binding name 'ns1__randomResponse' for type 'ns1:randomResponse' */
#ifndef SOAP_TYPE_ns1__randomResponse
#define SOAP_TYPE_ns1__randomResponse (10)
#endif

/* struct ns1__random has binding name 'ns1__random' for type 'ns1:random' */
#ifndef SOAP_TYPE_ns1__random
#define SOAP_TYPE_ns1__random (9)
#endif

/* struct ns1__authSecAssertResponse has binding name 'ns1__authSecAssertResponse' for type 'ns1:authSecAssertResponse' */
#ifndef SOAP_TYPE_ns1__authSecAssertResponse
#define SOAP_TYPE_ns1__authSecAssertResponse (8)
#endif

/* struct ns1__authSecAssert has binding name 'ns1__authSecAssert' for type 'ns1:authSecAssert' */
#ifndef SOAP_TYPE_ns1__authSecAssert
#define SOAP_TYPE_ns1__authSecAssert (7)
#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (100)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (99)
#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (93)
#endif

/* struct ns1__userDefineResponse * has binding name 'PointerTons1__userDefineResponse' for type 'ns1:userDefineResponse' */
#ifndef SOAP_TYPE_PointerTons1__userDefineResponse
#define SOAP_TYPE_PointerTons1__userDefineResponse (86)
#endif

/* struct ns1__userDefine * has binding name 'PointerTons1__userDefine' for type 'ns1:userDefine' */
#ifndef SOAP_TYPE_PointerTons1__userDefine
#define SOAP_TYPE_PointerTons1__userDefine (85)
#endif

/* struct ns1__userListGetResponse * has binding name 'PointerTons1__userListGetResponse' for type 'ns1:userListGetResponse' */
#ifndef SOAP_TYPE_PointerTons1__userListGetResponse
#define SOAP_TYPE_PointerTons1__userListGetResponse (82)
#endif

/* struct ns1__userListGet * has binding name 'PointerTons1__userListGet' for type 'ns1:userListGet' */
#ifndef SOAP_TYPE_PointerTons1__userListGet
#define SOAP_TYPE_PointerTons1__userListGet (81)
#endif

/* struct ns1__verifyUserRNResponse * has binding name 'PointerTons1__verifyUserRNResponse' for type 'ns1:verifyUserRNResponse' */
#ifndef SOAP_TYPE_PointerTons1__verifyUserRNResponse
#define SOAP_TYPE_PointerTons1__verifyUserRNResponse (78)
#endif

/* struct ns1__verifyUserRN * has binding name 'PointerTons1__verifyUserRN' for type 'ns1:verifyUserRN' */
#ifndef SOAP_TYPE_PointerTons1__verifyUserRN
#define SOAP_TYPE_PointerTons1__verifyUserRN (77)
#endif

/* struct ns1__userCancelResponse * has binding name 'PointerTons1__userCancelResponse' for type 'ns1:userCancelResponse' */
#ifndef SOAP_TYPE_PointerTons1__userCancelResponse
#define SOAP_TYPE_PointerTons1__userCancelResponse (74)
#endif

/* struct ns1__userCancel * has binding name 'PointerTons1__userCancel' for type 'ns1:userCancel' */
#ifndef SOAP_TYPE_PointerTons1__userCancel
#define SOAP_TYPE_PointerTons1__userCancel (73)
#endif

/* struct ns1__accessUnitGetResponse * has binding name 'PointerTons1__accessUnitGetResponse' for type 'ns1:accessUnitGetResponse' */
#ifndef SOAP_TYPE_PointerTons1__accessUnitGetResponse
#define SOAP_TYPE_PointerTons1__accessUnitGetResponse (70)
#endif

/* struct ns1__accessUnitGet * has binding name 'PointerTons1__accessUnitGet' for type 'ns1:accessUnitGet' */
#ifndef SOAP_TYPE_PointerTons1__accessUnitGet
#define SOAP_TYPE_PointerTons1__accessUnitGet (69)
#endif

/* struct ns1__userRNCertGetResponse * has binding name 'PointerTons1__userRNCertGetResponse' for type 'ns1:userRNCertGetResponse' */
#ifndef SOAP_TYPE_PointerTons1__userRNCertGetResponse
#define SOAP_TYPE_PointerTons1__userRNCertGetResponse (66)
#endif

/* struct ns1__userRNCertGet * has binding name 'PointerTons1__userRNCertGet' for type 'ns1:userRNCertGet' */
#ifndef SOAP_TYPE_PointerTons1__userRNCertGet
#define SOAP_TYPE_PointerTons1__userRNCertGet (65)
#endif

/* struct ns1__userModifyResponse * has binding name 'PointerTons1__userModifyResponse' for type 'ns1:userModifyResponse' */
#ifndef SOAP_TYPE_PointerTons1__userModifyResponse
#define SOAP_TYPE_PointerTons1__userModifyResponse (62)
#endif

/* struct ns1__userModify * has binding name 'PointerTons1__userModify' for type 'ns1:userModify' */
#ifndef SOAP_TYPE_PointerTons1__userModify
#define SOAP_TYPE_PointerTons1__userModify (61)
#endif

/* struct ns1__userVIDSetResponse * has binding name 'PointerTons1__userVIDSetResponse' for type 'ns1:userVIDSetResponse' */
#ifndef SOAP_TYPE_PointerTons1__userVIDSetResponse
#define SOAP_TYPE_PointerTons1__userVIDSetResponse (58)
#endif

/* struct ns1__userVIDSet * has binding name 'PointerTons1__userVIDSet' for type 'ns1:userVIDSet' */
#ifndef SOAP_TYPE_PointerTons1__userVIDSet
#define SOAP_TYPE_PointerTons1__userVIDSet (57)
#endif

/* struct ns1__challengeResponse * has binding name 'PointerTons1__challengeResponse' for type 'ns1:challengeResponse' */
#ifndef SOAP_TYPE_PointerTons1__challengeResponse
#define SOAP_TYPE_PointerTons1__challengeResponse (50)
#endif

/* struct ns1__challenge * has binding name 'PointerTons1__challenge' for type 'ns1:challenge' */
#ifndef SOAP_TYPE_PointerTons1__challenge
#define SOAP_TYPE_PointerTons1__challenge (49)
#endif

/* struct ns1__getPermissionByIdResponse * has binding name 'PointerTons1__getPermissionByIdResponse' for type 'ns1:getPermissionByIdResponse' */
#ifndef SOAP_TYPE_PointerTons1__getPermissionByIdResponse
#define SOAP_TYPE_PointerTons1__getPermissionByIdResponse (46)
#endif

/* struct ns1__getPermissionById * has binding name 'PointerTons1__getPermissionById' for type 'ns1:getPermissionById' */
#ifndef SOAP_TYPE_PointerTons1__getPermissionById
#define SOAP_TYPE_PointerTons1__getPermissionById (45)
#endif

/* struct ns1__randomResponse * has binding name 'PointerTons1__randomResponse' for type 'ns1:randomResponse' */
#ifndef SOAP_TYPE_PointerTons1__randomResponse
#define SOAP_TYPE_PointerTons1__randomResponse (42)
#endif

/* struct ns1__random * has binding name 'PointerTons1__random' for type 'ns1:random' */
#ifndef SOAP_TYPE_PointerTons1__random
#define SOAP_TYPE_PointerTons1__random (41)
#endif

/* struct ns1__getResultResponse * has binding name 'PointerTons1__getResultResponse' for type 'ns1:getResultResponse' */
#ifndef SOAP_TYPE_PointerTons1__getResultResponse
#define SOAP_TYPE_PointerTons1__getResultResponse (38)
#endif

/* struct ns1__getResult * has binding name 'PointerTons1__getResult' for type 'ns1:getResult' */
#ifndef SOAP_TYPE_PointerTons1__getResult
#define SOAP_TYPE_PointerTons1__getResult (37)
#endif

/* struct ns1__authSecAssertResponse * has binding name 'PointerTons1__authSecAssertResponse' for type 'ns1:authSecAssertResponse' */
#ifndef SOAP_TYPE_PointerTons1__authSecAssertResponse
#define SOAP_TYPE_PointerTons1__authSecAssertResponse (34)
#endif

/* struct ns1__authSecAssert * has binding name 'PointerTons1__authSecAssert' for type 'ns1:authSecAssert' */
#ifndef SOAP_TYPE_PointerTons1__authSecAssert
#define SOAP_TYPE_PointerTons1__authSecAssert (33)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stub Functions                                            *
 *                                                                            *
\******************************************************************************/

    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__authSecAssert(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__authSecAssert *ns1__authSecAssert, struct ns1__authSecAssertResponse *ns1__authSecAssertResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getResult(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__getResult *ns1__getResult, struct ns1__getResultResponse *ns1__getResultResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__random(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__random *ns1__random, struct ns1__randomResponse *ns1__randomResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getPermissionById(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__getPermissionById *ns1__getPermissionById, struct ns1__getPermissionByIdResponse *ns1__getPermissionByIdResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__challenge(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__challenge *ns1__challenge, struct ns1__challengeResponse *ns1__challengeResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getResult_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__getResult *ns1__getResult, struct ns1__getResultResponse *ns1__getResultResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__challenge_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__challenge *ns1__challenge, struct ns1__challengeResponse *ns1__challengeResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__userVIDSet(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__userVIDSet *ns1__userVIDSet, struct ns1__userVIDSetResponse *ns1__userVIDSetResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__userModify(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__userModify *ns1__userModify, struct ns1__userModifyResponse *ns1__userModifyResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__userRNCertGet(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__userRNCertGet *ns1__userRNCertGet, struct ns1__userRNCertGetResponse *ns1__userRNCertGetResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__accessUnitGet(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__accessUnitGet *ns1__accessUnitGet, struct ns1__accessUnitGetResponse *ns1__accessUnitGetResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__userCancel(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__userCancel *ns1__userCancel, struct ns1__userCancelResponse *ns1__userCancelResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__verifyUserRN(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__verifyUserRN *ns1__verifyUserRN, struct ns1__verifyUserRNResponse *ns1__verifyUserRNResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__userListGet(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__userListGet *ns1__userListGet, struct ns1__userListGetResponse *ns1__userListGetResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__userDefine(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__userDefine *ns1__userDefine, struct ns1__userDefineResponse *ns1__userDefineResponse);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getResult__(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__getResult *ns1__getResult, struct ns1__getResultResponse *ns1__getResultResponse);

/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/

    /** Web service operation '__ns1__authSecAssert' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__authSecAssert(struct soap*, struct ns1__authSecAssert *ns1__authSecAssert, struct ns1__authSecAssertResponse *ns1__authSecAssertResponse);
    /** Web service operation '__ns1__getResult' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__getResult(struct soap*, struct ns1__getResult *ns1__getResult, struct ns1__getResultResponse *ns1__getResultResponse);
    /** Web service operation '__ns1__random' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__random(struct soap*, struct ns1__random *ns1__random, struct ns1__randomResponse *ns1__randomResponse);
    /** Web service operation '__ns1__getPermissionById' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__getPermissionById(struct soap*, struct ns1__getPermissionById *ns1__getPermissionById, struct ns1__getPermissionByIdResponse *ns1__getPermissionByIdResponse);
    /** Web service operation '__ns1__challenge' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__challenge(struct soap*, struct ns1__challenge *ns1__challenge, struct ns1__challengeResponse *ns1__challengeResponse);
    /** Web service operation '__ns1__getResult_' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__getResult_(struct soap*, struct ns1__getResult *ns1__getResult, struct ns1__getResultResponse *ns1__getResultResponse);
    /** Web service operation '__ns1__challenge_' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__challenge_(struct soap*, struct ns1__challenge *ns1__challenge, struct ns1__challengeResponse *ns1__challengeResponse);
    /** Web service operation '__ns1__userVIDSet' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__userVIDSet(struct soap*, struct ns1__userVIDSet *ns1__userVIDSet, struct ns1__userVIDSetResponse *ns1__userVIDSetResponse);
    /** Web service operation '__ns1__userModify' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__userModify(struct soap*, struct ns1__userModify *ns1__userModify, struct ns1__userModifyResponse *ns1__userModifyResponse);
    /** Web service operation '__ns1__userRNCertGet' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__userRNCertGet(struct soap*, struct ns1__userRNCertGet *ns1__userRNCertGet, struct ns1__userRNCertGetResponse *ns1__userRNCertGetResponse);
    /** Web service operation '__ns1__accessUnitGet' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__accessUnitGet(struct soap*, struct ns1__accessUnitGet *ns1__accessUnitGet, struct ns1__accessUnitGetResponse *ns1__accessUnitGetResponse);
    /** Web service operation '__ns1__userCancel' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__userCancel(struct soap*, struct ns1__userCancel *ns1__userCancel, struct ns1__userCancelResponse *ns1__userCancelResponse);
    /** Web service operation '__ns1__verifyUserRN' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__verifyUserRN(struct soap*, struct ns1__verifyUserRN *ns1__verifyUserRN, struct ns1__verifyUserRNResponse *ns1__verifyUserRNResponse);
    /** Web service operation '__ns1__userListGet' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__userListGet(struct soap*, struct ns1__userListGet *ns1__userListGet, struct ns1__userListGetResponse *ns1__userListGetResponse);
    /** Web service operation '__ns1__userDefine' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__userDefine(struct soap*, struct ns1__userDefine *ns1__userDefine, struct ns1__userDefineResponse *ns1__userDefineResponse);
    /** Web service operation '__ns1__getResult__' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 __ns1__getResult__(struct soap*, struct ns1__getResult *ns1__getResult, struct ns1__getResultResponse *ns1__getResultResponse);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__authSecAssert(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getResult(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__random(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getPermissionById(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__challenge(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getResult_(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__challenge_(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__userVIDSet(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__userModify(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__userRNCertGet(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__accessUnitGet(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__userCancel(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__verifyUserRN(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__userListGet(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__userDefine(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getResult__(struct soap*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
